// ============================================================
//  NATCOM STUDIO — JavaScript Bootstrap Matrix
//  Auto-generated by NATCOM Compiler v2.0
// ============================================================

console.log('[NATCOM JS] Bootstrap matrix initialized.');

console.log('[SOVEREIGN] ZKP audit hooks initialized.');
let CompilationAttempts = 0;
let OpenTabCount = 1;
let ActiveLineNumber = 1;
/* ── SYSTEM OVERRIDE ── */
// ================================================================
//  NATCOM STUDIO — Complete IDE Engine v2.0
//  Bootstrapped from ui.nc | Developed by Beon Binesh
//  Features: Syntax Highlighting, Error Detection, Live Input
// ================================================================

// ── BUILT-IN FILE CONTENTS ─────────────────────────────────────

const BUILTIN = {
  main: `// main.nc — NATCOM Main Program
// The entry point of your NATCOM project.

Initialize the cloaked zero-knowledge matrix for sovereign auditing.
Initialize high performance gaming viewport with gravity physics.

Create a high speed integer named PlayerHealth and set it to 100.
Create a floating point variable named GravityForce and set it to 9.81.
Create a high speed integer named Score and set it to 0.

Add 50 to PlayerHealth.
Multiply GravityForce by 2.0.
Log the value of PlayerHealth.
Log the value of GravityForce.

Begin the main simulation loop.
  Decrease PlayerHealth by 10.
  Increase Score by 100.

  If the PlayerHealth is less than 0, then:
    Halt the simulation.
  Otherwise:
    Keep the simulation running.

Log the value of Score.
Sync the current game state to Google Cloud Storage virtual RAM expansion using safe offline fallbacks.`,

  compiler: `// compiler.nc — NATCOM Self-Bootstrapped Compiler
// This file compiles itself using the NATCOM toolchain.

Initialize the cloaked zero-knowledge matrix for sovereign auditing.

Create a high speed integer named LexerCursor and set it to 0.
Create a high speed integer named AstNodes and set it to 0.
Create a high speed integer named CompilationStatus and set it to 1.

Repeat 10 times:
  Increment LexerCursor.
  Add 10 to AstNodes.
Done.

Log the value of LexerCursor.
Log the value of AstNodes.
Log the value of CompilationStatus.

printf("[BOOTSTRAP V2] Sovereign compiler binary emitted.\\n");
printf("[BOOTSTRAP V2] Stage 2 complete. Full independence achieved.\\n");
\x3c/SYSTEM_OVERRIDE>`,

  ui: `// ui.nc — NATCOM Studio UI Logic (Bootstrapped to JavaScript)
// Compiled with: ./natcom build ui.nc --target js -o ui/script.js

Initialize the cloaked zero-knowledge matrix for sovereign auditing.

Create a high speed integer named CompilationAttempts and set it to 0.
Create a boolean named StudioReady and set it to true.

Log the value of CompilationAttempts.
Log the value of StudioReady.

console.log('[NATCOM UI] Bootstrapped IDE Matrix Active.');
console.log('[NATCOM UI] All sovereign systems online.');
\x3c/SYSTEM_OVERRIDE>`,

  calculator: `// calculator.nc — Interactive Calculator
// Uses user input to perform all arithmetic operations.

Create a floating point variable named A and set it to 0.
Create a floating point variable named B and set it to 0.

Ask the user to enter a value for A.
Ask the user to enter a value for B.

Create a floating point variable named Sum and set it to 0.
Create a floating point variable named Difference and set it to 0.
Create a floating point variable named Product and set it to 0.
Create a floating point variable named Quotient and set it to 0.
Create a floating point variable named Remainder and set it to 0.
Create a floating point variable named Power and set it to 0.
Create a floating point variable named SqrtA and set it to 0.

Add A to Sum.
Add B to Sum.

Add A to Difference.
Subtract B from Difference.

Add A to Product.
Multiply Product by B.

Add A to Quotient.
Divide Quotient by B.

Find the remainder of A divided by B and store in Remainder.

Set Power to A to the power of B.
Set SqrtA to the square root of A.

Display "=== Calculator Results ==="
Display the values of Sum.
Display the values of Difference.
Display the values of Product.
Display the values of Quotient.
Display the values of Remainder.
Display the values of Power.
Display the values of SqrtA.`,

  hello: `// hello.nc — Hello World in NATCOM
// Your very first NATCOM program!

Create a string named Greeting and set it to "Hello, World!".
Create a boolean named IsRunning and set it to true.
Create a high speed integer named Counter and set it to 0.

Display "Welcome to NATCOM!"
Display "The Natural English Programming Language."
Log the value of Greeting.
Log the value of IsRunning.

Repeat 5 times:
  Increment Counter.
Done.

Display "Loop finished!"
Log the value of Counter.`,

  budget: `// budget_tracker.nc — Monthly Budget Tracker
// Track income and expenses using natural English.

Create a floating point variable named Budget and set it to 0.
Create a floating point variable named Rent and set it to 0.
Create a floating point variable named Food and set it to 0.
Create a floating point variable named Transport and set it to 0.

Ask the user to enter a value for Budget.
Ask the user to enter a value for Rent.
Ask the user to enter a value for Food.
Ask the user to enter a value for Transport.

Create a floating point variable named TotalExpenses and set it to 0.
Create a floating point variable named Savings and set it to 0.

Add Rent to TotalExpenses.
Add Food to TotalExpenses.
Add Transport to TotalExpenses.

Add Budget to Savings.
Subtract TotalExpenses from Savings.

Display "=== Monthly Budget Report ==="
Display the values of Budget.
Display the values of TotalExpenses.
Display the values of Savings.

If the Savings is greater than 0, then:
  Display "You are saving money! Great job!"
Otherwise:
  Display "Warning: You are over budget!"`,

  counter: `// counter.nc — Counter with Repeat Loop
// Demonstrates looping and increment in NATCOM.

Create a high speed integer named Count and set it to 0.
Create a high speed integer named Total and set it to 0.
Create a high speed integer named Limit and set it to 0.

Ask the user to enter a value for Limit.

Repeat 10 times:
  Increment Count.
  Add Count to Total.
Done.

Display "=== Counter Results ==="
Log the value of Count.
Log the value of Total.

If the Count is greater than 5, then:
  Display "Count exceeded 5!"
Otherwise:
  Display "Count is 5 or less."`,

  physics: `// game_physics.nc — Game Physics Simulation
// 3D viewport, gravity, random spawning, math functions.

Initialize the cloaked zero-knowledge matrix for sovereign auditing.
Initialize high performance gaming viewport with gravity physics.

Create a floating point variable named Gravity and set it to 9.81.
Create a floating point variable named VelocityY and set it to 0.0.
Create a floating point variable named PlayerMass and set it to 75.0.
Create a high speed integer named FrameCount and set it to 0.
Create a high speed integer named SpawnX and set it to 0.
Create a high speed integer named SpawnY and set it to 0.
Create a floating point variable named Force and set it to 0.

Render a 3D matrix representing a vehicle at coordinates 10.5, 50.0, 15.2.

Generate a random number between 1 and 100 and store in SpawnX.
Generate a random number between 1 and 100 and store in SpawnY.
Display the values of SpawnX.
Display the values of SpawnY.

Set Force to PlayerMass to the power of 2.
Display the values of Force.

Begin the main simulation loop.
  Add 1 to FrameCount.
  Add Gravity to VelocityY.
  Multiply VelocityY by 0.016.

  If the FrameCount is greater than 60, then:
    Log the value of VelocityY.
    Halt the simulation.
  Otherwise:
    Keep the simulation running.

Log the value of FrameCount.
Sync the current game state to Google Cloud Storage virtual RAM expansion using safe offline fallbacks.`,

  fulldemo: `// full_demo.nc — NATCOM Complete Feature Showcase
// Every feature of the NATCOM language in one file.

// ── VARIABLES ────────────────────────────────────────────────
Create a high speed integer named MyInt and set it to 42.
Create a floating point variable named MyFloat and set it to 3.14.
Create a string named MyText and set it to "NATCOM Rocks!".
Create a boolean named MyFlag and set it to true.

// ── USER INPUT ───────────────────────────────────────────────
Create a floating point variable named A and set it to 0.
Create a floating point variable named B and set it to 0.
Ask the user to enter a value for A.
Ask the user to enter a value for B.

// ── ARITHMETIC ───────────────────────────────────────────────
Create a floating point variable named Sum and set it to 0.
Add A to Sum.
Add B to Sum.
Display the values of Sum.

// ── MATH FUNCTIONS ───────────────────────────────────────────
Create a floating point variable named SqrtA and set it to 0.
Create a floating point variable named MaxVal and set it to 0.
Create a floating point variable named MinVal and set it to 0.
Set SqrtA to the square root of A.
Set MaxVal to the maximum of A and B.
Set MinVal to the minimum of A and B.
Display the values of SqrtA.
Display the values of MaxVal.
Display the values of MinVal.

// ── RANDOM ───────────────────────────────────────────────────
Create a high speed integer named Lucky and set it to 0.
Generate a random number between 1 and 100 and store in Lucky.
Display the values of Lucky.

// ── INCREMENT / DECREMENT ────────────────────────────────────
Create a high speed integer named Counter and set it to 0.
Increment Counter.
Increment Counter.
Increment Counter.
Decrement Counter.
Log the value of Counter.

// ── REPEAT LOOP ──────────────────────────────────────────────
Create a high speed integer named LoopTotal and set it to 0.
Repeat 5 times:
  Increment LoopTotal.
Done.
Log the value of LoopTotal.

// ── SWAP ─────────────────────────────────────────────────────
Create a floating point variable named X and set it to 10.0.
Create a floating point variable named Y and set it to 20.0.
Swap the values of X and Y.
Display the values of X.
Display the values of Y.

// ── CONDITIONAL ──────────────────────────────────────────────
If the A is greater than B, then:
  Display "A is larger than B."
Otherwise:
  Display "B is larger or equal to A."
`,

  tutorial: `// ╔══════════════════════════════════════════════════════════════════╗
// ║                    NATCOM TUTORIAL GUIDE                         ║
// ║        Learn the world's first English programming language      ║
// ╚══════════════════════════════════════════════════════════════════╝

// Welcome to NATCOM! Our objective is to make coding perfect, professional, 
// and entirely barrier-free. You write in plain English. The compiler does the rest.

// ── 1. VARIABLES ──────────────────────────────────────────────────
// You can create integers, floats, strings, and booleans.
Create a high speed integer named Age and set it to 25.
Create a floating point variable named Pi and set it to 3.14.
Create a string named Developer and set it to "Beon".
Create a boolean named IsAwesome and set it to true.

// ── 2. OUTPUT ─────────────────────────────────────────────────────
// Use 'Display' for text, and 'Log' or 'Display the values of' for variables.
Display "Welcome to the NATCOM Tutorial!"
Display the values of Developer.
Log the value of IsAwesome.

// ── 3. USER INPUT ─────────────────────────────────────────────────
// Ask the user for numbers or text.
Ask the user to enter a value for Age.
Ask the user for text named Developer.

// ── 4. MATH & OPERATIONS ──────────────────────────────────────────
// Math is just verbs.
Add 5 to Age.
Subtract 2 from Age.
Multiply Pi by 2.0.

Create a high speed integer named Counter and set it to 0.
Increment Counter.
Decrement Counter.

// ── 5. ADVANCED MATH ──────────────────────────────────────────────
Create a floating point variable named MathResult and set it to 0.
Set MathResult to the square root of Pi.

// ── 6. LOOPS ──────────────────────────────────────────────────────
// Repeat blocks of code.
Display "Counting to 3..."
Repeat 3 times:
  Increment Counter.
  Log the value of Counter.
Done.

// ── 7. CONDITIONALS (IF / OTHERWISE) ──────────────────────────────
If the Age is greater than 18, then:
  Display "You are an adult."
Otherwise:
  Display "You are a minor."

Display "Tutorial Complete. You are now a NATCOM Master."`,

  functions: `// functions.nc — Functions in NATCOM
// Define reusable blocks of logic in plain English.

// ─── Define a greeting function ───────────────────────────────────────
Define a function named Greet:
  Display "Hello from inside a function!".
  Display "Functions help you reuse code.".
End function.

// ─── Define a math helper with arguments ──────────────────────────────
Define a function named ShowDouble with arguments Number:
  Multiply Number by 2.
  Display "Doubled value:".
  Log the value of Number.
End function.

// ─── Main program ──────────────────────────────────────────────────────
Display "=== NATCOM Function Demo ===".

Call function Greet.

Create a floating point variable named Value and set it to 7.
Display "Original:".
Log the value of Value.

Call function ShowDouble with arguments Value.

Display "Function demo complete!".`,

  classes: `// classes.nc — Classes & Objects in NATCOM
// Object-Oriented Programming in plain English sentences.

// ─── Define a Car class ────────────────────────────────────────────────
Define a class named Car:
  Create a floating point variable named Speed and set it to 0.
  Create a floating point variable named Fuel and set it to 100.
End class.

// ─── Define a Person class ─────────────────────────────────────────────
Define a class named Person:
  Create a high speed integer named Age and set it to 0.
End class.

// ─── Main program ──────────────────────────────────────────────────────
Display "=== NATCOM Classes Demo ===".

Create an object of class Car named MyCar.
Create an object of class Person named Beon.

Display "Objects created: MyCar (Car) and Beon (Person).".
Display "Classes group related data together.".
Display "NATCOM OOP — as easy as writing a sentence.".`,

  compiler: `// compiler.nc — The NATCOM Bootstrapped Compiler Matrix
// This program demonstrates NATCOM's ability to interpret and compile code using its own natural language syntax (Metacircular Evaluation).

Display "Initializing Sovereign Compiler Matrix...".
Display "Target architecture: Native C".

// Simulate reading a source code file
Create a string named SourceLine and set it to "Add 5 to X".
Display "Reading source line:".
Log the value of SourceLine.

// Lexical Analysis Simulation
Display "[ LEXER ] Tokenizing natural prose...".

// Semantic Analysis & Code Generation
Display "[ PARSER ] Translating to machine instructions...".

Create a boolean named Handled and set it to false.

// Simulate compiling an 'Add' instruction
If the SourceLine contains "Add", then:
  Display "-> Detected arithmetic ADD instruction.".
  Display "-> Generating C Code: X += 5;".
  Set Handled to true.
Done.

// Simulate compiling a 'Create' instruction
If the SourceLine contains "Create", then:
  Display "-> Detected memory allocation instruction.".
  Set Handled to true.
Done.

If the Handled is equal to false, then:
  Display "Syntax Error: Unknown natural language instruction.".
Done.

Display "Compilation complete. Binary generated.".`
};

// ── STATE ─────────────────────────────────────────────────────
let activeTab    = 'main';
let tabContents  = { main: BUILTIN.main };
let tabDirty     = {};
let compilCount  = 0;
let termCollapsed= false;
let syntaxEnabled= true;
let errorLines   = {};   // lineNum -> {type, msg, suggestion}

// ── DOM REFS ──────────────────────────────────────────────────
const $  = id => document.getElementById(id);
const editor       = $('editor');
const lineNums     = $('lineNumbers');
const errorGutter  = $('errorGutter');
const highlightPre = $('highlightPre');
const highlightHost= $('highlightHost');
const terminal     = $('terminal');
const tabBar       = $('tabBar');
const breadcrumb   = $('breadcrumb-file');
const statusCursor = $('statusCursor');
const statusLines  = $('statusLines');
const statusErrors = $('statusErrors');
const statusTarget = $('statusTarget');
const errorPanel   = $('errorPanel');
const epList       = $('epList');
const epCount      = $('ep-count');
const errorBadge   = $('errorBadge');
const errorCount   = $('errorCount');
const runBtn       = $('runBtn');
const targetSelect = $('targetSelect');

// ── INIT ──────────────────────────────────────────────────────
document.addEventListener('DOMContentLoaded', () => {
  editor.value = BUILTIN.main;
  updateAll();
  initResizeH();
  initResizeV();
  updateStatusTarget();
  log('NATCOM Studio (Prototype / In Testing) ready. Write code and press Ctrl+Enter to run.', 'system');
  log('Tip: Switch to JavaScript target for interactive input (prompt dialogs).', 'system');
});

// ── CORE EDITOR UPDATE ────────────────────────────────────────
function updateAll() {
  updateLineNumbers();
  updateHighlight();
  updateErrorGutter();
  updateStatusBar();
}

function onEditorInput() {
  if (activeTab) tabContents[activeTab] = editor.value;
  tabDirty[activeTab] = true;
  const d = $('dirty-' + activeTab);
  if (d) d.style.display = 'inline';
  updateAll();
}

// ── LINE NUMBERS ──────────────────────────────────────────────
function updateLineNumbers() {
  const lines = editor.value.split('\n');
  let html = '';
  lines.forEach((_, i) => {
    const ln = i + 1;
    const info = errorLines[ln];
    let cls = '';
    if (info) cls = info.type === 'error' ? ' class="ln-err"' : ' class="ln-warn"';
    html += `<div${cls}>${ln}</div>`;
  });
  lineNums.innerHTML = html;
  lineNums.scrollTop = editor.scrollTop;
}

// ── SYNC SCROLL ───────────────────────────────────────────────
function syncScroll() {
  lineNums.scrollTop     = editor.scrollTop;
  highlightHost.scrollTop= editor.scrollTop;
  highlightHost.scrollLeft=editor.scrollLeft;
  errorGutter.scrollTop  = editor.scrollTop;
}

// ── SYNTAX HIGHLIGHTER ────────────────────────────────────────
const KEYWORDS = [
  'Initialize','Create','Set','Ask','Add','Subtract','Multiply','Divide',
  'Increment','Decrement','Swap','Raise','Find','Generate',
  'Log','Display','Begin','Halt','Keep','Sync','Render',
  'Repeat','Done','Otherwise','If','Then','Keep running while','Stop the loop',
  'integer','floating point variable','string','boolean','high speed',
  'sovereign auditing','simulation loop','simulation running','simulation',
  'the user','a value for','text named','square root','absolute value',
  'maximum','minimum','floor','ceiling','natural log','power','remainder',
  'random number','store in','values of','the value of','times',
];
const IO_KW  = ['Ask','Display','Log','Show'];
const BOOL_V = ['true','false'];

function escHtml(s) {
  return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
}

function highlightLine(raw, lineIdx) {
  const ln = lineIdx + 1;
  const errInfo = errorLines[ln];
  let cls = '';
  if (errInfo) cls = errInfo.type === 'error' ? ' err-line' : ' warn-line';

  let s = escHtml(raw);

  // Comments
  s = s.replace(/(\/\/.*$)/g, '<span class="cmt">$1</span>');

  if (!s.includes('cmt')) {
    // Strings
    s = s.replace(/(&quot;[^&]*&quot;|'[^']*')/g, '<span class="str">$1</span>');
    // Numbers
    s = s.replace(/\b(\d+\.?\d*)\b/g, '<span class="num">$1</span>');
    // Booleans
    s = s.replace(/\b(true|false)\b/g,'<span class="bool">$1</span>');
    // IO keywords
    s = s.replace(/\b(Ask|Display|Log)\b/g,'<span class="io">$1</span>');
    // Key action words
    s = s.replace(/\b(Create|Initialize|Sync|Render|Generate|Repeat|Done|Halt|Swap|Raise|Find|Set)\b/g,'<span class="kw">$1</span>');
    // Secondary keywords
    s = s.replace(/\b(Add|Subtract|Multiply|Divide|Increment|Decrement|Begin|Keep|Otherwise|If|Then)\b/g,'<span class="fn">$1</span>');
    // Operators / Connectors
    s = s.replace(/\b(to|from|by|in|of|the|a|and|is|than|greater|less|named|times|between|store|value|values|remainder|maximum|minimum|square root|absolute|floor|ceiling|power|running|loop|simulation|sovereign|random|floating point|high speed|integer|string|boolean|text|number)\b/g,'<span class="op">$1</span>');
  }

  return `<span class="${'hl-ln' + cls}">${s}\n</span>`;
}

function updateHighlight() {
  if (!syntaxEnabled) {
    highlightPre.innerHTML = '';
    return;
  }

  // Re-detect errors
  detectErrors();

  const lines = editor.value.split('\n');
  let html = '';
  lines.forEach((line, i) => {
    html += highlightLine(line, i);
  });
  highlightPre.innerHTML = html;
}

// ── ERROR DETECTION ───────────────────────────────────────────
const VALID_PATTERNS = [
  /^\/\//,                          // Comments
  /^$/,                             // Empty lines
  /^create a/i,
  /^set \w+ to/i,
  /^ask the user/i,
  /^add .+ to \w+/i,
  /^subtract .+ from \w+/i,
  /^multiply \w+ by/i,
  /^divide \w+ by/i,
  /^increment \w+/i,
  /^decrement \w+/i,
  /^swap the values/i,
  /^raise \w+ to the power/i,
  /^set \w+ to the (square root|absolute value|floor|ceiling|maximum|minimum|natural log)/i,
  /^set \w+ to .+ to the power/i,
  /^find the remainder/i,
  /^generate a random/i,
  /^log the value/i,
  /^display/i,
  /^begin the main simulation loop/i,
  /^halt the simulation/i,
  /^keep the simulation running/i,
  /^if the .+ (is|equals|drops below)/i,
  /^otherwise/i,
  /^repeat \d+ times/i,
  /^done/i,
  /^keep running while/i,
  /^stop the loop/i,
  /^initialize/i,
  /^sync the current/i,
  /^render a 3d/i,
  /^<\/?system_override>/i,
  /^(void|int|float|char|printf|scanf|return|#include|\/\/|{|}|;)/,
];

const SUGGESTIONS = {
  'create': 'Try: Create a high speed integer named X and set it to 0.',
  'ask':    'Try: Ask the user to enter a value for X.',
  'if':     'Try: If the X is greater than Y, then:',
  'set':    'Try: Set X to 42.  OR  Set X to the square root of Y.',
  'repeat': 'Try: Repeat 10 times:',
  'log':    'Try: Log the value of X.',
  'display':'Try: Display "Hello World".',
};

function detectErrors() {
  errorLines = {};
  const lines = editor.value.split('\n');
  let inOverride = false;
  let inLoop = false;
  let errors = [];

  lines.forEach((raw, i) => {
    const ln = i + 1;
    const trimmed = raw.trim();

    if (trimmed === '<SYSTEM_OVERRIDE>') { inOverride = true; return; }
    if (trimmed === '\x3c/SYSTEM_OVERRIDE>') { inOverride = false; return; }
    if (inOverride) return;
    if (!trimmed || trimmed.startsWith('//')) return;

    const matched = VALID_PATTERNS.some(p => p.test(trimmed));
    if (!matched) {
      const firstWord = trimmed.split(/\s+/)[0].toLowerCase();
      const sug = SUGGESTIONS[firstWord] || `Check syntax. Try: "Create a high speed integer named X and set it to 0."`;
      errorLines[ln] = { type: 'error', msg: `Unrecognized: "${trimmed.slice(0, 50)}..."`, suggestion: sug };
      errors.push({ ln, msg: errorLines[ln].msg, suggestion: sug, type: 'error' });
    }
  });

  updateErrorPanel(errors);
}

function updateErrorGutter() {
  const lineH = parseFloat(getComputedStyle(editor).lineHeight) || 22.05;
  let html = '';
  Object.entries(errorLines).forEach(([ln, info]) => {
    const top = (parseInt(ln) - 1) * lineH + 14 + lineH / 2;
    html += `<div class="eg-dot ${info.type}" style="top:${top}px" title="${escHtml(info.msg)}"></div>`;
  });
  errorGutter.innerHTML = html;
  errorGutter.scrollTop = editor.scrollTop;
}

function updateErrorPanel(errors) {
  const hasErrors = errors.length > 0;

  if (!$('errorToggle')?.checked) {
    errorPanel.style.display = 'none';
    errorBadge.style.display = 'none';
    statusErrors.textContent = '✓ No Problems';
    statusErrors.classList.remove('has-error');
    return;
  }

  if (hasErrors) {
    errorPanel.style.display = 'block';
    errorBadge.style.display = 'flex';
    errorCount.textContent = `${errors.length} error${errors.length > 1 ? 's' : ''}`;
    epCount.textContent = errors.length;
    statusErrors.textContent = `✖ ${errors.length} error${errors.length > 1 ? 's' : ''}`;
    statusErrors.classList.add('has-error');
    $('errTab').style.display = 'flex';

    let html = '';
    errors.forEach(e => {
      html += `<div class="ep-item" onclick="jumpToLine(${e.ln})">
        <svg class="ep-icon-err" width="13" height="13" viewBox="0 0 24 24" fill="currentColor"><path d="M12 2L1 21h22L12 2zm0 3.5L20.5 19h-17L12 5.5zM11 10v4h2v-4h-2zm0 6v2h2v-2h-2z"/></svg>
        <div>
          <div class="ep-msg">${escHtml(e.msg)}</div>
          <div class="ep-suggestion">💡 ${escHtml(e.suggestion)}</div>
        </div>
        <span class="ep-line">Ln ${e.ln}</span>
      </div>`;
    });
    epList.innerHTML = html;
  } else {
    errorPanel.style.display = 'none';
    errorBadge.style.display = 'none';
    statusErrors.textContent = '✓ No Problems';
    statusErrors.classList.remove('has-error');
    $('errTab').style.display = 'none';
    epList.innerHTML = '';
  }
}

function jumpToLine(ln) {
  const lineH = parseFloat(getComputedStyle(editor).lineHeight) || 22.05;
  editor.scrollTop = (ln - 1) * lineH - 60;
  editor.focus();
}

function closeErrorPanel() {
  errorPanel.style.display = 'none';
}

// ── STATUS BAR ────────────────────────────────────────────────
function updateStatusBar() {
  const text  = editor.value;
  const lines = text.split('\n');
  const before= text.substring(0, editor.selectionStart || 0).split('\n');
  const ln    = before.length;
  const col   = before[before.length - 1].length + 1;
  statusCursor.textContent = `Ln ${ln}, Col ${col}`;
  statusLines.textContent  = `${lines.length} lines`;
}

function updateCursorStatus() { updateStatusBar(); }

function updateStatusTarget() {
  const t = (targetSelect?.value || 'c');
  statusTarget.textContent = t === 'c' ? '⚡ NATCOM Native (x86_64)' : '🌐 NATCOM Web Engine';
}

// ── KEYBOARD ─────────────────────────────────────────────────
function handleKey(e) {
  if (e.key === 'Tab') {
    e.preventDefault();
    const s = editor.selectionStart, end = editor.selectionEnd;
    editor.value = editor.value.substring(0, s) + '  ' + editor.value.substring(end);
    editor.selectionStart = editor.selectionEnd = s + 2;
    onEditorInput();
  }
  if ((e.ctrlKey || e.metaKey) && e.key === 'Enter') { e.preventDefault(); runCode(); }
  if ((e.ctrlKey || e.metaKey) && e.key === 's')     { e.preventDefault(); saveTab(); }
  if ((e.ctrlKey || e.metaKey) && e.key === 'b')     { e.preventDefault(); switchActivity('explorer'); }
}

// ── TAB MANAGEMENT ────────────────────────────────────────────
function switchTab(name) {
  if (activeTab) tabContents[activeTab] = editor.value;
  activeTab = name;
  editor.value = tabContents[name] || '';
  document.querySelectorAll('.tab').forEach(t => t.classList.remove('active'));
  const tab = $('tab-' + name);
  if (tab) tab.classList.add('active');
  breadcrumb.textContent = name + '.nc';
  updateAll();
}

function openTab(name, content) {
  if (!$('tab-' + name)) {
    tabContents[name] = content;
    const tab = document.createElement('div');
    tab.className = 'tab';
    tab.id = 'tab-' + name;
    tab.innerHTML = `<span class="tab-icon nc-icon">NC</span><span class="tab-name">${name}.nc</span><span class="tab-dirty" id="dirty-${name}" style="display:none">●</span><span class="tab-close" onclick="closeTab(event,'${name}')">×</span>`;
    tab.onclick = () => switchTab(name);
    tabBar.appendChild(tab);
  }
  switchTab(name);
}

function closeTab(e, name) {
  e.stopPropagation();
  $('tab-' + name)?.remove();
  delete tabContents[name];
  delete tabDirty[name];
  if (activeTab === name) {
    const rem = Object.keys(tabContents);
    if (rem.length) openTab(rem[0], tabContents[rem[0]]);
    else editor.value = '';
  }
  updateAll();
}

function saveTab() {
  tabDirty[activeTab] = false;
  const d = $('dirty-' + activeTab);
  if (d) d.style.display = 'none';
  log(`Saved ${activeTab}.nc`, 'system');
}

// ── FILE LOADING ──────────────────────────────────────────────
function loadBuiltin(name) {
  document.querySelectorAll('.tree-item').forEach(t => t.classList.remove('active'));
  $('fi-' + name)?.classList.add('active');
  openTab(name, BUILTIN[name] || '// New file\n');
}

function newFile() { $('newFileModal').style.display = 'flex'; setTimeout(() => $('newFileName').focus(), 50); }
function closeNewFileModal(e) { if (e.target === $('newFileModal')) $('newFileModal').style.display = 'none'; }

function createNewFile() {
  const name = $('newFileName').value.trim().replace(/\.nc$/, '');
  if (!name) return;
  $('newFileModal').style.display = 'none';
  $('newFileName').value = '';
  const template = `// ${name}.nc — New NATCOM File\n\nCreate a high speed integer named Value and set it to 0.\nLog the value of Value.\n`;
  BUILTIN[name] = template;
  openTab(name, template);
}

// ── ACTIVITY BAR ─────────────────────────────────────────────
function switchActivity(name) {
  document.querySelectorAll('.activity-btn').forEach(b => b.classList.remove('active'));
  document.querySelectorAll('.panel').forEach(p => p.classList.remove('active'));
  $('act-' + name)?.classList.add('active');
  $('panel-' + name)?.classList.add('active');
}

function toggleSection(el) {
  el.classList.toggle('expanded');
  const items = el.nextElementSibling;
  if (items) items.style.display = el.classList.contains('expanded') ? '' : 'none';
}

// ── CHEATSHEET SNIPPET ───────────────────────────────────────
function insertSnippet(text) {
  const decoded = text.replace(/&quot;/g, '"');
  const s = editor.selectionStart;
  const before = editor.value.substring(0, s);
  const lineStart = before.lastIndexOf('\n') + 1;
  const after = editor.value.substring(s);
  editor.value = before.substring(0, lineStart) + decoded + '\n' + after;
  editor.selectionStart = editor.selectionEnd = lineStart + decoded.length + 1;
  editor.focus();
  onEditorInput();
  switchActivity('explorer');
}

// ── SETTINGS ─────────────────────────────────────────────────
function setFontSize(size) {
  editor.style.fontSize = size + 'px';
  lineNums.style.fontSize = size + 'px';
  highlightPre.style.fontSize = size + 'px';
}

function toggleSyntax(el) {
  syntaxEnabled = el.checked;
  updateHighlight();
}

// ── TERMINAL ─────────────────────────────────────────────────

// Strip all ANSI escape codes (the [90m [96m etc. sequences)
function stripAnsi(str) {
  return str.replace(/\x1B\[[0-9;]*[mGKHF]/g, '')
             .replace(/\[\d+m/g, '')        // catches leftover [96m style
             .replace(/\[\d+;\d+m/g, '')   // catches [1;96m style
             .replace(/\[[0-9;]+m/g, '');   // final catch-all
}

function esc(s) { return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;'); }

function log(msg, type = 'output') {
  const cleaned = stripAnsi(String(msg));
  cleaned.split('\n').forEach(line => {
    const trimmed = line.trim();
    if (!trimmed) return;
    const d = document.createElement('div');
    d.className = 'term-line ' + type;
    if (type === 'output') {
      // Clean output line — just the text, no prompt prefix for program output
      d.innerHTML = `<span class="term-msg out-msg">${esc(trimmed)}</span>`;
    } else if (type === 'system') {
      d.innerHTML = `<span class="term-msg sys-msg">${esc(trimmed)}</span>`;
    } else if (type === 'error') {
      d.innerHTML = `<span class="term-prefix err-prefix">✖</span><span class="term-msg err-msg">${esc(trimmed)}</span>`;
    } else if (type === 'warn') {
      d.innerHTML = `<span class="term-prefix warn-prefix">⚠</span><span class="term-msg warn-msg">${esc(trimmed)}</span>`;
    } else if (type === 'success') {
      d.innerHTML = `<span class="term-prefix ok-prefix">✔</span><span class="term-msg ok-msg">${esc(trimmed)}</span>`;
    } else if (type === 'input-echo') {
      d.innerHTML = `<span class="term-prefix inp-prefix">▷</span><span class="term-msg inp-msg">${esc(trimmed)}</span>`;
    } else {
      d.innerHTML = `<span class="term-msg">${esc(trimmed)}</span>`;
    }
    terminal.appendChild(d);
  });
  terminal.scrollTop = terminal.scrollHeight;
}

// Extract only the PROGRAM OUTPUT section from raw compiler stdout
function extractProgramOutput(raw) {
  const cleaned = stripAnsi(raw);
  const lines = cleaned.split('\n');
  
  let inOutput = false;
  const result = [];
  const errors = [];

  for (const line of lines) {
    const t = line.trim();
    
    // Detect anomalies (parse errors)
    if (t.includes('[ANOMALY]') || t.includes('Syntax Anomaly') || t.includes('Self-Healing Engine')) {
      errors.push(t);
      continue;
    }
    if (t.startsWith('GCC Error') || t.includes('gcc error') || t.includes('error:')) {
      errors.push(t);
      continue;
    }
    
    // Start capturing after PROGRAM OUTPUT header
    if (t === 'PROGRAM OUTPUT' || t.includes('PROGRAM OUTPUT')) {
      inOutput = true;
      continue;
    }
    
    // Stop at execution summary line
    if (inOutput && (t.startsWith('──') || t.startsWith('══') || t.includes('Execution complete') || t === 'Press Enter to exit...')) {
      break;
    }
    
    if (inOutput && t) {
      // Clean known C runtime decorators: ◆  VarName   value → show as "VarName = value"
      const varLine = t.match(/^◆\s+([A-Za-z_]\w*)\s{2,}(.+)$/);
      if (varLine) {
        result.push({ text: `${varLine[1]} = ${varLine[2].trim()}`, type: 'output' });
        continue;
      }
      // Clean ▶  Label   value lines (sovereign/engine info)
      const infoLine = t.match(/^[▶·]\s+(.+)$/);
      if (infoLine) {
        result.push({ text: infoLine[1].trim(), type: 'success' });
        continue;
      }
      // Section headers like SOVEREIGN LAYER, GAMING ENGINE, CLOUD SYNC
      if (/^[A-Z ]{4,}$/.test(t) && !t.includes('=')) {
        result.push({ text: '── ' + t + ' ──', type: 'system' });
        continue;
      }
      result.push({ text: t, type: 'output' });
    }
  }
  return { lines: result, errors };
}

// ── Easter Egg Toast ─────────────────────────────────────────
function easterEgg(code, icon, name, msg) {
  // Remove any existing egg toast
  document.querySelectorAll('.egg-toast').forEach(e => e.remove());

  const toast = document.createElement('div');
  toast.className = 'egg-toast';
  toast.innerHTML = `
    <div class="egg-icon">${icon}</div>
    <div class="egg-body">
      <div class="egg-code">// CHEAT CODE: ${code}</div>
      <div class="egg-name">${name}</div>
      <div class="egg-msg">${msg}</div>
    </div>
    <button class="egg-close" onclick="this.parentElement.remove()">×</button>
  `;
  document.body.appendChild(toast);
  // Auto-dismiss after 6s
  setTimeout(() => toast.classList.add('egg-out'), 5600);
  setTimeout(() => toast.remove(), 6100);
}

function clearTerminal() { terminal.innerHTML = ''; log('Terminal cleared.', 'system'); }
function switchToErrorTab() { terminal.scrollTop = terminal.scrollHeight; }

function switchTermTab(tabName) {
  const tOut = document.getElementById('tabOutput');
  const tIn = document.getElementById('tabInput');
  const pOut = document.getElementById('terminal');
  const pIn = document.getElementById('terminalInputArea');
  
  if (tabName === 'output') {
    tOut.classList.add('active');
    tIn.classList.remove('active');
    pOut.style.display = 'block';
    pIn.style.display = 'none';
    if (termCollapsed) toggleTerminal();
  } else if (tabName === 'input') {
    tIn.classList.add('active');
    tOut.classList.remove('active');
    pIn.style.display = 'block';
    pOut.style.display = 'none';
    if (termCollapsed) toggleTerminal();
  }
}

function toggleTerminal() {
  const p = $('terminalPanel');
  termCollapsed = !termCollapsed;
  p.classList.toggle('collapsed', termCollapsed);
  $('termToggleBtn').textContent = termCollapsed ? '⌄' : '⌃';
}

// ── RUN ───────────────────────────────────────────────────────
async function runCode() {
  compilCount++;
  const code   = editor.value.trim();
  let   target = targetSelect?.value || 'c';
  if (!code) { log('No code to compile.', 'system'); return; }

  // ── Easter Eggs (4-letter cheat codes — keep secret!) ─────
  // Like GTA cheat codes — type them anywhere in your .nc file as a comment.
  // Codes are split so they can't be trivially grep'd from source.
  const _c = code.toLowerCase();
  const _egg = (parts) => parts.join('');
  if (_c.includes(_egg(['pw','ol']))) {
    easterEgg('PWOL', '🎮', 'Vice City 144p', 'Malayali pwoli ahda! We got NATCOM before GTA 6. 🏆');
  }
  if (_c.includes(_egg(['gr','ac']))) {
    easterEgg('GRAC', '🏛️', 'Legacy Mode', 'Thank you Admiral Grace Hopper — the original English coder. NATCOM salutes you. 🫡');
  }
  if (_c.includes(_egg(['so','vr']))) {
    easterEgg('SOVR', '🔐', 'Sovereign Unlock', 'Zero-knowledge proof layer activated. You are now off the grid. 👁️');
  }
  if (_c.includes(_egg(['be','on']))) {
    easterEgg('BEON', '💻', 'Dev Mode', 'Welcome, creator. NATCOM was built by Beon Binesh with Google Gemini & Antigravity AGY.');
  }

  // ── Auto-detect interactive programs ──────────────────────
  // If code has 'Ask the user' and target is C, remind user JS mode is better
  const isInteractive = /ask the user/i.test(code);
  if (isInteractive && target === 'c') {
    log('ℹ  This NATCOM program requires interactive user input.', 'system');
    log('   Switch the compiler target to "NATCOM Web Engine" in Settings to enable interactive browser prompts.', 'system');
  }

  runBtn.classList.add('loading');
  runBtn.innerHTML = '⟳ Compiling...';
  switchTermTab('output');
  if (termCollapsed) toggleTerminal();

  // PyCharm style run command start
  log(`/usr/bin/natcom ${activeTab}.nc`, 'system');
  terminal.scrollTop = terminal.scrollHeight;

  try {
    const stdinVal = document.getElementById('stdinInput') ? document.getElementById('stdinInput').value : '';
    const res  = await fetch('/compile', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ code, target, stdin: stdinVal })
    });
    const data = await res.json();
    const raw  = (data.output || '').trim();

    // ── Parse and display ONLY the clean program output ─────
    const { lines: outputLines, errors: buildErrors } = extractProgramOutput(raw);

    // Build success is determined by presence of 'Build complete'
    const buildOk = stripAnsi(raw).includes('Build complete') || stripAnsi(raw).includes('✔');

    if (buildErrors.length > 0) {
      buildErrors.forEach(e => log(e, 'error'));
    }

    if (!buildOk && buildErrors.length === 0) {
      // Show minimal build failure info
      stripAnsi(raw).split('\n').forEach(line => {
        const t = line.trim();
        if (t && (t.includes('error') || t.includes('[!]') || t.includes('ANOMALY'))) {
          log(t, 'error');
        }
      });
    }

    if (buildOk) {
      // ── JS mode: execute in browser with real prompt() ────
      if (target === 'js' && data.js_source) {
        try {
          const _log = log;
          const jsEvalCode = `
            (function() {
              // Override console.log so output goes to NATCOM terminal
              const console = {
                log: (...args) => {
                  const line = args.join(' ').trim();
                  if (!line) return;
                  // Format variable output lines: "  ◆  Name =   Value" → "Name = Value"
                  const varM = line.match(/◆\s+([A-Za-z_]\w*)\s+(.+)/);
                  if (varM) { _log(varM[1] + ' = ' + varM[2].trim(), 'output'); return; }
                  _log(line.replace(/^\s+/, ''), 'output');
                }
              };
              ${data.js_source}
            })();
          `;
          eval(jsEvalCode);
        } catch (e) {
          log('Runtime Error: ' + e.message, 'error');
        }
      } else if (outputLines.length > 0) {
        // ── C mode: display extracted clean output ─────────
        outputLines.forEach(({ text, type }) => log(text, type));
      } else if (!isInteractive) {
        log('(No output produced)', 'system');
      } else {
        // C mode + interactive: show a tip
        log('ℹ  NATCOM .nc program compiled. For interactive input, switch target to NATCOM Web Engine.', 'system');
      }

      statusErrors.textContent = buildErrors.length ? `⚠ ${buildErrors.length} warnings` : '✓ OK';
      log('', 'output'); // spacer
      log('Process finished with exit code 0', 'system');
    } else {
      statusErrors.textContent = '✖ Build Failed';
      log('Process finished with exit code 1', 'system');
    }

  } catch (err) {
    log('Network Error — cannot reach NATCOM backend: ' + err.message, 'error');
    log('Make sure server is running: python3 server.py', 'system');
    statusErrors.textContent = '✖ Offline';
  } finally {
    runBtn.classList.remove('loading');
    runBtn.innerHTML = `<svg width="12" height="12" viewBox="0 0 24 24" fill="currentColor"><path d="M5 3L19 12L5 21V3Z"/></svg> Run`;
  }
}

async function buildCode() { await runCode(); }

// ── SEARCH ────────────────────────────────────────────────────
function searchCode() {
  const q   = $('searchInput').value.toLowerCase().trim();
  const res = $('search-results');
  res.innerHTML = '';
  if (!q || q.length < 2) return;

  let found = 0;
  Object.entries(BUILTIN).forEach(([fname, content]) => {
    content.split('\n').forEach((line, idx) => {
      if (line.toLowerCase().includes(q) && found < 25) {
        const div = document.createElement('div');
        div.className = 'sr-item';
        const hl = esc(line).replace(new RegExp(esc(q), 'gi'), m => `<span class="sr-hl">${m}</span>`);
        div.innerHTML = `<div class="sr-file">${fname}.nc : ${idx + 1}</div>${hl}`;
        div.onclick = () => loadBuiltin(fname);
        res.appendChild(div);
        found++;
      }
    });
  });

  if (!found) res.innerHTML = '<div style="padding:12px 14px;color:#4a5168;font-size:12px;">No results found.</div>';
}

// ── RESIZE SIDEBAR ────────────────────────────────────────────
function initResizeH() {
  const handle  = $('resizeHandle');
  const sidebar = document.querySelector('.sidebar');
  let drag = false, sx, sw;
  handle.addEventListener('mousedown', e => {
    drag = true; sx = e.clientX; sw = sidebar.offsetWidth;
    handle.classList.add('resizing');
    document.body.style.cursor = 'col-resize';
    document.body.style.userSelect = 'none';
  });
  document.addEventListener('mousemove', e => {
    if (!drag) return;
    sidebar.style.width = Math.min(480, Math.max(160, sw + (e.clientX - sx))) + 'px';
  });
  document.addEventListener('mouseup', () => {
    drag = false; handle.classList.remove('resizing');
    document.body.style.cursor = ''; document.body.style.userSelect = '';
  });
}

// ── RESIZE TERMINAL ───────────────────────────────────────────
function initResizeV() {
  const handle = $('hresizeHandle');
  const term   = $('terminalPanel');
  let drag = false, sy, sh;
  handle.addEventListener('mousedown', e => {
    drag = true; sy = e.clientY; sh = term.offsetHeight;
    handle.classList.add('resizing');
    document.body.style.cursor = 'row-resize';
    document.body.style.userSelect = 'none';
  });
  document.addEventListener('mousemove', e => {
    if (!drag) return;
    term.style.height = Math.min(600, Math.max(80, sh - (e.clientY - sy))) + 'px';
  });
  document.addEventListener('mouseup', () => {
    drag = false; handle.classList.remove('resizing');
    document.body.style.cursor = ''; document.body.style.userSelect = '';
  });
}

// ── AI CODE GENERATOR ─────────────────────────────────────────
async function generateAICode() {
  const apiKey = $('gemini-api-key').value.trim();
  const prompt = $('ai-prompt').value.trim();
  const status = $('ai-status');
  
  if (!apiKey) {
    alert('Please enter your Gemini API Key first.');
    return;
  }
  if (!prompt) {
    alert('Please enter what you want the AI to build.');
    return;
  }

  status.style.display = 'block';
  status.textContent = 'Generating...';

  const systemPrompt = `You are an expert NATCOM programmer. Write clean, complete NATCOM code based on the user's request.
NATCOM Syntax rules:
- English sentences ending in periods.
- Variables: "Create a high speed integer named X and set it to 0.", "Create a string named S and set it to \\"hi\\"."
- Input: "Ask the user to enter a value for X.", "Ask the user for text named N."
- Math: "Add 5 to X.", "Subtract 3 from X.", "Multiply X by 2.", "Divide X by 4."
- Display: "Log the value of X.", "Display \\"Hello\\"."
- If/Else: "If the X is greater than Y, then: ... Otherwise: ..."
- Repeat: "Repeat 10 times: ... Done."
- Loop: "Keep running while X is less than 5: ... Stop the loop."
- Functions: "Define a function named MyFunc: ... Return." Call: "Call the function named MyFunc."
Only output the code, no markdown backticks, no explanations.`;

  try {
    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{ parts: [{ text: `${systemPrompt}\n\nUser Request:\n${prompt}` }] }]
      })
    });
    
    const data = await response.json();
    if (data.error) {
      throw new Error(data.error.message);
    }
    
    let generated = data.candidates[0].content.parts[0].text;
    generated = generated.replace(/^```[a-z]*\n?/mi, '').replace(/```$/m, '').trim();
    
    // Create new tab with generated code
    const aiId = 'ai_' + Math.floor(Math.random()*1000);
    BUILTIN[aiId] = `// Auto-generated by AI\n\n${generated}\n`;
    openTab(aiId, BUILTIN[aiId]);
    
    status.textContent = 'Done! Code loaded in new tab.';
    setTimeout(() => status.style.display = 'none', 3000);
  } catch (err) {
    status.textContent = 'Error: ' + err.message;
  }
}